"use client";

import React, { useState } from "react";
import { Modal } from "@/components/ui/modal";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ShieldAlert, Download, X, Plus } from "lucide-react";

export function DisavowManagerModal({ isOpen, onClose }: { isOpen: boolean; onClose: () => void }) {
  const [entries, setEntries] = useState([
    { domain: "spammy-directory-xyz.net", reason: "High toxic spam score (88%)" },
    { domain: "malware-links-fake.org", reason: "Malware domain classification" }
  ]);

  if (!isOpen) return null;

  const handleExportTxt = () => {
    const lines = ["# Google Search Console Disavow File", "# Generated by SEOPilot AI Engine"];
    entries.forEach((e) => lines.push(`domain:${e.domain}`));
    const content = lines.join("\n");

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "disavow.txt";
    a.click();
  };

  return (
    <div className="fixed inset-0 z-50 bg-background/80 backdrop-blur-md flex items-center justify-center p-4">
      <div className="w-full max-w-md rounded-2xl border border-border bg-popover p-6 shadow-2xl glass-panel space-y-6 animate-in fade-in zoom-in-95">
        <div className="flex items-center justify-between border-b border-border pb-4">
          <div className="flex items-center gap-2 text-destructive font-bold">
            <ShieldAlert className="w-5 h-5" />
            <h3 className="font-bold text-base text-foreground">Google Disavow Manager</h3>
          </div>
          <button onClick={onClose} className="text-muted-foreground hover:text-foreground">
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="space-y-3 text-xs">
          <span className="font-bold text-foreground block">Flagged Toxic Domains to Disavow:</span>
          {entries.map((e, idx) => (
            <div key={idx} className="p-3 rounded-xl bg-destructive/10 border border-destructive/20 space-y-1">
              <div className="font-mono font-bold text-destructive">domain:{e.domain}</div>
              <div className="text-[10px] text-muted-foreground">{e.reason}</div>
            </div>
          ))}
        </div>

        <div className="flex items-center justify-between pt-2 border-t border-border">
          <Button variant="ghost" onClick={onClose}>Cancel</Button>
          <Button onClick={handleExportTxt} className="gap-2 glow-primary">
            <Download className="w-4 h-4" /> Export disavow.txt
          </Button>
        </div>
      </div>
    </div>
  );
}
